exclude: >
  (?x)^(
      data/
  )
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.12.0]

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0  # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
        - id: terraform_fmt
        # - id: terraform_tfsec install is suboptimal
