version: '3'
services:
  redis:
    restart: always
    image: redis
    volumes:
    - ./data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
  frontend:
    restart: always
    image: thinkst/canarytokens
    build: ./canarytokens/
    env_file:
     - frontend-v3.env
    volumes:
    - ./uploads:/uploads/
    - log-volume:/logs
    container_name: frontend
    command: bash -c "cd frontend; poetry run python -m uvicorn app:app --host 0.0.0.0 --port 8082"
  switchboard:
    restart: always
    image: thinkst/canarytokens
    ports:
     - "5354:53"
     - "5354:53/udp"
     - "25:25"
     - "3306:3306"
     - "6443:6443"
     - "51820:51820/udp"
    env_file:
     - switchboard-v3.env
    volumes:
      - ./frontend-v3.env:/frontend.env:ro
      - ./switchboard-v3.env:/switchboard.env:ro
      - ./uploads:/uploads/
      - log-volume:/logs
    container_name: switchboard
    command: bash -c "cd switchboard; rm -f switchboard.pid; poetry run twistd -noy switchboard.tac --pidfile=switchboard.pid"
  nginx:
    restart: always
    image: thinkst/canarytokens_nginx
    build: ./nginx/
    ports:
     - "80:80"
    depends_on:
      - "frontend"
      - "switchboard"
    container_name: nginx
    command: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
volumes:
  log-volume: