version: '3'
services:
  redis:
    restart: always
    image: redis
    volumes:
    - ./data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
  frontend:
    restart: always
    image: thinkst/canarytokens:dev_v3
    env_file:
     - frontend-v3.env
    volumes:
    - ./uploads:/uploads/
    - log-volume:/logs
    container_name: frontend
    command: bash -c "/venv/bin/python -m uvicorn app:app --host 0.0.0.0 --port 8082"
  switchboard:
    restart: always
    image: thinkst/canarytokens:dev_v3
    ports:
     - "5354:53"
     - "5354:53/udp"
     - "25:25"
     - "3306:3306"
     - "6443:6443"
     - "51820:51820/udp"
    env_file:
     - switchboard-v3.env
    volumes:
      - ./frontend-v3.env:/frontend.env:ro
      - ./switchboard-v3.env:/switchboard.env:ro
      - ./uploads:/uploads/
      - log-volume:/logs
    container_name: switchboard
    command: bash -c "rm -f switchboard.pid; /venv/bin/twistd -noy switchboard.tac --pidfile=switchboard.pid"
  nginx:
    restart: always
    image: thinkst/certbot-nginx
    build: ./certbot-nginx/
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - "frontend"
      - "switchboard"
    container_name: nginx
    env_file:
     - certbot.env
    volumes:
     - /etc/letsencrypt/:/etc/letsencrypt/
volumes:
  log-volume: