FROM nginx
MAINTAINER Marco Slaviero <marco@thinkst.com>
LABEL Description="This image is provides the http proxy for Canarytokens" Vendor="Thinkst Applied Research" Version="1.1"
COPY nginx.conf /etc/nginx/nginx.conf
